### ISSUE TITLE
Null loader still trying to load sass files

### ISSUE THREAD

**Issue by evandegr** [webpack-contrib/null-loader#2]
```
target: 'node',
module: {
        loaders: [
            {
                test: /\.scss$/,
                loader: 'null-loader'
            }
        ]
    }
```

I try to load a button.js file which refers to a button.scss file. I get the following error:

```
ERROR in ./app/framework/src/components/button.scss
Module build failed: file to import not found or unreadable: variables
Current dir:  (1:9)
 @ ./app/framework/src/components/button.js 25:0-24
BUILD COMPLETE
[16:49:44] Finished 'test' after 6.38 s
/web/node_modules/babel-core/lib/babel/transformation/file/index.js:614
      throw err;
            ^
SyntaxError: /web/app/framework/src/components/button.scss: Unexpected token (1:0)
> 1 | @import 'variables';
    | ^
  2 | 
  3 | $button-sizes: (
  4 |     'loner-padding'       : 42px,
    at Parser.pp.raise (/web/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/web/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseDecorator (/web/node_modules/babel-core/lib/acorn/src/statement.js:146:10)
    at Parser.pp.parseDecorators (/web/node_modules/babel-core/lib/acorn/src/statement.js:132:31)
    at Parser.pp.parseStatement (/web/node_modules/babel-core/lib/acorn/src/statement.js:46:10)
    at Parser.parseStatement (/web/node_modules/babel-core/lib/acorn/plugins/flow.js:639:22)
    at Parser.pp.parseTopLevel (/web/node_modules/babel-core/lib/acorn/src/statement.js:22:21)
    at Object.parse (/web/node_modules/babel-core/lib/acorn/src/index.js:106:12)
    at exports.default (/web/node_modules/babel-core/lib/babel/helpers/parse.js:66:19)
    at File.parse (/web/node_modules/babel-core/l    at Object.require.extensions..js (/web/test_setup.js:40:11)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/web/app/framework/src/test.entrypoint.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.require.extensions..js (/web/test_setup.js:40:11)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /web/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/web/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/web/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/web/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Mocha exited with code 1
    at ChildProcess.<anonymous> (/web/node_modules/gulp-spawn-mocha/lib/index.js:58:28)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

If I remove the scss import it works fine, however isn't null loader just supposed to prevent that from loading at all?

**Comment by stefanbuck** [comment]
@evandegr I run into the same issue. What was the problem?

**Comment by resurtm** [comment]
@stefanbuck @evandegr Have you guys solved this issue? Thanks!

**Comment by devniel** [comment]
same problem here, did you solve it ?

**Comment by Astra-RX** [comment]
Still broken on excluding modules / css
